fkirc/skip-duplicate-actions

- .github/workflows/test.yml
- README.md
- action.yml
> Remove required token

- .github/workflows/test.yml
- README.md
- action.yml
- dist/index.js
- src/index.ts
> Optional feature skip_concurrent_trigger

- dist/index.js
- src/index.ts
Workaround for https://github.com/fkirc/skip-duplicate-actions/issues/45
> Catch random fetch failures

- .github/workflows/test.yml
- README.md
Additional guarding against malfunctioning like https://github.com/fkirc/skip-duplicate-actions/issues/45
> Improve fault tolerance

- .github/workflows/test.yml
- README.md
This wouldn't be good during an initial integration
> Continue on error

- .github/workflows/build.yml
- .github/workflows/test.yml
- README.md
- action.yml
- dist/index.js
- src/index.ts
Optional fix for https://github.com/fkirc/skip-duplicate-actions/issues/50
> Optional concurrent skipping

- .github/workflows/build.yml
- .github/workflows/test.yml
- CHANGELOG.md
- README.md
- action.yml
- dist/index.js
- src/index.ts
A solution for https://github.com/fkirc/skip-duplicate-actions/issues/63 and https://github.com/fkirc/skip-duplicate-actions/issues/53.
Besides, it also removes some shaky and obscure code.
> V3: Rethink Concurrent Skipping

- .github/workflows/test.yml
- README.md
- action.yml
- dist/index.js
- src/index.ts
Solution for https://github.com/fkirc/skip-duplicate-actions/issues/69
> Skip outdated runs

- .github/workflows/test.yml
- README.md
- action.yml
- dist/index.js
- src/index.ts
Solution for https://github.com/fkirc/skip-duplicate-actions/issues/72.
From now on, every feature should be optional.
> Make duplicate skipping optional

- .github/workflows/build.yml
- dist/index.js
- src/index.ts
bugfix: the logic problem of getBooleanInput (#82 )
> bugfix: the logic problem of getBooleanInput

- README.md
- action.yml
- dist/index.js
- src/index.ts
Don't cancel _all_ same_content runs.
Fix to issue #90 (untested, sorry).
> Only cancel new same_content run

- dist/index.js
- src/index.ts
> Compare workflows by run number instead of creation date

- dist/index.js
- src/index.ts
Context: https://github.com/fkirc/skip-duplicate-actions/issues/124
> Fix same_content_new bug (runs would be inappropriately skipped)

- dist/index.js
- package-lock.json
Tested in a private repository - everything works 👍
(Instead of single pull requests from dependabot, also there are already newer versions)
> Update all dependencies

- .github/workflows/check-dist.yml
- .github/workflows/test.yml
- dist/index.js
- package-lock.json
✅  Tested in a private repository
> Update all dependencies & rebuild

- README.md
> Enhance documentation of input values

- .github/workflows/check-dist.yml
- .github/workflows/test.yml
- dist/index.js
- package-lock.json
- package.json
* Update all dependencies & rebuild.
* Beautify workflows by adding explicit naming to workflow, jobs and steps.
@fkirc This means you'd need to update the required checks in the settings.
> Update dependencies, rebuild & beautify workflows

- dist/index.js
- package-lock.json
```console
@types/node                       16.11.43  16.11.47
@typescript-eslint/eslint-plugin    5.30.4    5.31.0
@typescript-eslint/parser           5.30.4    5.31.0
eslint                              8.19.0    8.21.0
eslint-plugin-github                 4.3.6     4.3.7
```
> Update dependencies & rebuild

- README.md
- action.yml
- dist/index.js
- src/main.ts
As it is used by GitHub
Also slightly enhance some log messages
> Consistent usage of term 'workflow run'

- .github/FUNDING.yml
Hey @fkirc, what do you think about adding a funding option to this repository?
This would give the users of this action the possibility to sponsor us which in turn might allow us to spend more time on this project.
For this you'd need to set up a GitHub Sponsor profile...
Feel free to close this pull request in case you would rather not have this.
> Add funding option

- .github/workflows/test.yml
- dist/index.js
- package-lock.json
- src/main.ts
To make debugging and traceability easier.
> Add a job summary

- README.md
Only run when both should_skip flags are false
> Fix an example in README.md
